display_icon_titles:
  default: true
  description:
    en: "Display titles"

icons_size:
  default: 1.2
  description:
    en: "This setting changes the CSS font-size property of the icons (unit is em)"

tab_1_settings:
  default: "Home, home, /"
  description:
    en: "Format is: <code>&lt;title&gt;, &lt;FA5 icon&gt;, &lt;relative url or route name&gt;, &lt;enabled? default true (optional)&gt;, &lt;anonymous? default false (optional)&gt;</code>"

tab_2_settings:
  default: "Profile, user, userActivity.index, false"

tab_3_settings:
  default: "Messages, envelope, userPrivateMessages.user.index, false"

tab_4_settings:
  default: "Bookmarks, bookmark, userActivity.bookmarks, false"

tab_5_settings:
  default: "Preferences, cog, preferences.account, false"

tab_6_settings:
  default: "Notifications, comment, userNotifications.index, false, false"

extend_fa5_icons:
  type: list
  default: ""
  description:
    en: "Use this setting to add any icons you want to use that are not included in the default FA5 icons subset"

match_url_params:
  default: false
  description:
    en: "Match full url without trim params"
